<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ include file="/global/header.jsp" %>
<body>
<div style="padding:15px;padding-top:0;">
    <div class="row">
        <%@ include file="/global/topnav.jsp" %>
        <div class="text-left loginCon" style="max-width:1080px;">
            <h2 class="loginTit text-center">Terms of Use</h2>
            <hr>
            <p>BIEX LIMITED (hereinafter referred to as BIEX) is a company registered in the British Virgin Islands under the applicable laws and regulations. With its platform, including the operating website: www.biex.com and the related mobile applications (hereinafter referred to as "the platform"), BIEX provides its users with services concerning digital currency trading.</p>
            <p>IMPORTANT NOTES:</p>
            <p>Digital asset trading can be extremely risky. It is open throughout the day without up and down limits, and the prices are subject to drastic fluctuation under the influence of market makers and worldwide government policies. Furthermore, due to the drafting or modification of laws, regulations and regulatory documents in various countries, digital asset trading may be suspended or banned at any time. You should carefully consider and be totally clear about the above risks and bear the resulting loss. BIEX does not assume any responsibility in these cases.</p>
            <p>I. Range of applicationThis service is only available to users of age 18 years or older, hence you have to declare and ensure that you are at least 18 years old and have not been deprived of the corresponding rights. In addition, the platform temporarily does not provide services to the following countries and regions: Cuba, Iran, North Korea, Iraq, Belarus, Sudan, Libya, Mainland China and the United States of America. If you fail to meet these requirements, please do not use our service.</p>
            <p>II. Service Content and Rules The platform provides only online trading platform services for you to conduct digital currency transaction activities (including but not limited to digital asset trading), and the platform itself does not participate as a buyer or seller in the sale of digital assets.</p>
            <p>1.) You have the right to view the real-time quotes and trading information of the various digital asset products on the platform, and to submit digital asset trading instructions and complete the digital asset trading through the platform.</p>
            <p>2.) You should abide by the laws and regulations, and should properly use and keep your account number, login password, fund password, and the phone number bound at registering, as well as the verification code received by your mobile phone. For your use of the platform’s account, login password, fund password, verification code for any operation and the corresponding consequences, you have to take full responsibility. When you find that the account, login password, fund password, or the verification code of the platform might be used by unauthorized third parties, or if you find any other account security issues, you should effectively inform the platform and request the platform to suspend the services for the account in question. The platform reserves the right to take action on your request within a reasonable time, but for any consequences (including but not limited to any loss on your part) occurred before action taken, the platform assumes no responsibility whatsoever. You may not share with others the platform’s account by granting, lending, leasing, transferring or any other means without the consent of the platform.</p>
            <p>3.) While viewing the trading information on the platform, you should carefully read ALL the content, including but not limited to price, quota, fee, sale orientation (buy or sell) etc. If you fully accept all the content of the trading information, you can first confirm the information’s correction and then submit the trading commission.</p>
            <p>4.) If you use any methods, such as but not limited to technological means, system vulnerabilities etc., to make the commissioned trading conclude at a price deviated from the normal market quotation, or to make the account of assets unreasonably increase or decrease, BIEX has the right to freeze the relevant accounts permanently.</p>
            <p>III. Service Change, Interruption or Termination</p>
            <p>This Agreement shall remain in effect unless the platform terminates it or you apply to terminate it and obtain consent of the platform. If you violate this Agreement or the relevant rules, or at the request of relevant laws, regulations, government departments, the platform reserves the right to terminate this Agreement, close your account or limit your use of the platform.</p>
            <p>1.) Given the specific characteristics of network services, you agree that the platform has the right to change, interrupt or terminate some or all of the network services at any time, and in the event of such changes, interruptions or termination, the platform will not be subject to any further notice to the users and will not assume any responsibility for any user or any third party.</p>
            <p>2.) You understand that the platform needs to regularly or irregularly carry on overhauls or maintenance to the network service providing platforms (such as Internet websites, mobile networks, etc.) or the related equipment. If, due to such circumstance, the network service is interrupted within a reasonable time, the platform will need not to assume any responsibility but should notify in advance to the best of its ability.</p>
            <p>3.) Based on the unilateral independent judgment, and in the circumstances that it is considered that the trading might be vulnerable to dangers etc., the platform has the right to suspend, interrupt or terminate the provision of all or part of the services under this Agreement to you without prior notice, and to remove or delete the registration information without any liability to you or any third party. The foregoing circumstances include but are not limited to:</p>
            <p>(1) The platform does not consider the personal information provided by you to be authentic, valid or complete;</p>
            <p>(2) When the platform finds any trading abnormal or in doubt or in danger of breaking the law;</p>
            <p>(3) The platform considers that your account is involved in money laundering, pyramid selling, being falsely used or in other situations that the platform deems as risky;</p>
            <p>(4) Any other circumstances that based on trading security and other reasons, according to the platform’s unilateral judgment that all or part of the membership services under this Agreement provided to you need to be suspended, interrupted or terminated, and the registration information need to be removed or </p>
            <p>IV. Service Fee</p>
            <p>1.) When users use the service, according to the corresponding rules, the platform shall be entitled to charge the user service fees and interest generated by the loan. The platform has the right to formulate and adjust the service fees and the loan interest. Specific service fees and loan interest shall be notified by the billing method listed when the user start using the service or by other written agreement between users and the platform.</p>
            <p>2.) Unless otherwise stated or agreed, the user agrees that the platform shall be entitled to deduct directly the above service fees and loan interest from the assets of the user's account.</p>
            <p>V. Limitation of Liability and Exemption</p>
            <p>We assume no responsibility for any service inability or service delay caused by network equipment maintenance, the failure of information network, computer, telecommunication or other systems, power failure, weather, accidents, strikes, labor disputes, insurrections, uprisings, riots, shortage of productivity or means of production, floods, storms, explosions, wars, causes of banks or other partners, collapse of digital asset markets, government actions, orders of judicial or administrative authorities, and other causes that are not within our control or under our control, or causes from third parties. And for your resulting loss, we are not responsible either. We cannot guarantee that all the information, programs, texts, etc. contained in the platform are completely safe and free from the interference and destruction of any malicious programs such as viruses and Trojans. Therefore, it’s your own decisions to log in and use any service of the platform or download and use any program, information, data, etc., and you shall bear the risks and possible losses.</p>
        </div>
    </div>
</div>
<%@ include file="/global/footer.jsp" %>
</body>
</html>